apiVersion: v1
kind: ReplicationController
metadata:
  name: producer-controller
spec:
  replicas: 5
  template:
    metadata:
      name: demo-producer
      labels:
        app: demo-producer
    spec:
      containers:
        - name: demo-producer
          image: demo-producer:demo
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
